approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
author_approval: required
approve_by_comment: true
reviewers:
  members: "all"
  name: default
  required: 2
